package dev.slne.surf.roleplay.fabric.ui.icon

import com.google.gson.JsonParser
import dev.slne.surf.roleplay.fabric.RoleplayClient
import net.minecraft.resources.Identifier

/**
 * The position of one icon in the Lucide atlas.
 *
 * @property u the left edge of the icon in the atlas, in texture pixels
 * @property v the top edge of the icon in the atlas, in texture pixels
 * @property categories the Lucide categories of the icon, empty for aliases
 */
data class IconCell(val u: Float, val v: Float, val categories: List<String>)

/**
 * The name index of the Lucide icon atlas.
 *
 * @property cell the side length of one icon in the atlas, in texture pixels
 * @property width the width of the atlas, in texture pixels
 * @property height the height of the atlas, in texture pixels
 * @property icons the icons and aliases keyed by name
 * @property names the names of the icons, without aliases, sorted
 */
class LucideIndex private constructor(
    val cell: Int,
    val width: Int,
    val height: Int,
    private val icons: Map<String, IconCell>,
    val names: List<String>,
) {
    /**
     * Looks up an icon or alias by name.
     *
     * @param name the Lucide name, such as `trash` or its alias `trash-2`
     * @return the icon's cell, or `null` if no icon has that name
     */
    fun find(name: String): IconCell? = icons[name]

    /**
     * Parses and loads indexes.
     */
    companion object {
        /**
         * The texture of the atlas.
         */
        val ATLAS: Identifier = Identifier.fromNamespaceAndPath(RoleplayClient.MOD_ID, "textures/gui/lucide.png")

        /**
         * The index shipped in the mod jar, loaded on first use; an empty index if it is missing.
         */
        val bundled: LucideIndex by lazy {
            val stream = LucideIndex::class.java.getResourceAsStream("/assets/${RoleplayClient.MOD_ID}/lucide/index.json")
            if (stream == null) {
                RoleplayClient.log.error("The Lucide icon index is missing from the mod jar")
                LucideIndex(0, 0, 0, emptyMap(), emptyList())
            } else {
                stream.use { parse(it.readBytes().toString(Charsets.UTF_8)) }
            }
        }

        /**
         * Parses an index generated by the build.
         *
         * @param json the index JSON
         * @return the index
         */
        fun parse(json: String): LucideIndex {
            val root = JsonParser.parseString(json).asJsonObject
            val cell = root["cell"].asInt
            val icons = mutableMapOf<String, IconCell>()
            val names = mutableListOf<String>()
            for ((name, value) in root["icons"].asJsonObject.entrySet()) {
                val entry = value.asJsonObject
                val categories = entry["categories"]?.asJsonArray?.map { it.asString } ?: emptyList()
                icons[name] = IconCell(entry["x"].asInt * cell.toFloat(), entry["y"].asInt * cell.toFloat(), categories)
                if (!entry.has("alias")) names += name
            }
            return LucideIndex(cell, root["width"].asInt, root["height"].asInt, icons, names.sorted())
        }
    }
}
